name: avenger_gallery
description: A new Flutter application.

dependencies:

  cloud_firestore:
  flutter_staggered_grid_view:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/avenger.png
    - assets/images/marvel.jpg
    - assets/images/ant-man.png
    - assets/images/blackwidow.png
    - assets/images/captainamerica.png
    - assets/images/doctorstrange.png
    - assets/images/hawkeye.png
    - assets/images/hulk.png
    - assets/images/ironman.png
    - assets/images/marvellogo.png
    - assets/images/panther.png
    - assets/images/spiderman.png
    - assets/images/thor.png
    - assets/images/wolverine.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
        - family: Poppins
          fonts:
             - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
               weight: 600
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
        - family: Comfortaa
          fonts:
             - asset: assets/fonts/Comfortaa/Comfortaa-Bold.ttf
        - family: Montserrat
          fonts:
             - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf

  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
